from tkinter import *
def oppo_8():
    import tkinter
    from PIL import ImageTk, Image
    #import QR_Code 
    b=Tk()
    b.title("Oppo Reno 5 Pro")
    b.minsize(520,655)
    b.maxsize(520,655)
    def qr():
        b.minsize(500,600)
        b.maxsize(500,600)
        image1 = Image.open('qrcode.jpg')
        test = ImageTk.PhotoImage(image1)
        label1 = tkinter.Label(image=test)
        label1.image = test
        label1.pack()
        b.mainloop()
    def details():
        print("==========================================================================")
        print("\nOriginal Oppo Reno 5 Pro 5G Smartphone 12G+256GB 6.55  90HZ Dimensity1000+ Android11 64MP")
        print("Camera Octa Core 65W Super VOOC FaceID 4350mAh OTG NFC Support Google by-（Real Star Technology） (Black 12+256)")
        print("\nModel Name : Reno 5 Pro")
        print("Wireless Carrier : Unlocked for All Carriers")
        print("Brand : Oppo")
        print("Form Factor : Smartphone")
        print("Memory Storage Capacity : 256 GB")
        print("Cellular Technology : 5G, 4G, 3G, 2G")
        print("Operating System : Android 10.0")
        print("Color : Black 12+256")
        print("SIM card slot count : Single SIM")
        print("Display Size  : 6.5")
        print("Other camera features : Front")
        print("Package Dimensions : 6.85 x 3.62 x 2.44 inches; 6.21 Ounces")
        print("Manufacturer : OPPO Dealer\n")
        print("\nAbout this item\n")
        print("1.) AI Radiance Video Beauty | Radiance portrait video | FDF full-dimensional portrait video technology system | AI video")
        print("enhancement | 32 million water light mirror + 64 million water light portrait four shots | Star Diamond Craft (Reno Glow2.0) |")
        print("7.6mm ultra-thin feel MTK 1000+ processor 30 months of smooth use | AI exquisite ID photo | Soloop recording | Lightning start |")
        print("Dolby Atmos | 4350mAh battery | 65W super charging | Five-dimensional super-sensing gaming experience |")
        print("2.) Offical firmware with supporting Multi-Language & Pre-install GooglePlay Store & OTA Update,100% Guarantee Original Oppo Mobile Phone")
        print("3.) Package Included OPPO Reno 5 pro*1 Adapter*1 Headset *1 USB-C Charge Cable*1 Important Info. Booklet with Warranty Card *1")
        print("Quick Start Guide *1 SIM Card Ejector *1 Protect Film *1 Case *1")
        print("4.) 2G: GSM 850/900/1800/1900MHz 2G: CDMA BC0 （ 800MHz ） 3G: CDMA2000 BC0 （ 800MHz） 3G: UMTS(WCDMA) bands")
        print("1/2/4/5/6/8/19 4G: TD-LTE bands 34/38/39/40/41(160MHz) 4G: LTE FDD bands 1/2/3/4/5/7/8/12/17/18/19/26 5G:")
        print("n1/n3/n41/n77/n78/n79 (The actual network and frequency band usage depends on the deployment of local operators, n1 and")
        print("n3 need to be supported by the operator through OTA upgrade after release)")
        print("5.) You will enjoy a 12-Month Warranty and Free Lifetime Technical Support(except man-made damage to the battery, screen,")
        print("motherboards)please check whether your carrier supports the bands of this model before purchasing;")
    def buy_now():
            qr()
    image1 = Image.open('oppo.jpg').resize((400,600))
    test = ImageTk.PhotoImage(image1)
    label1 = tkinter.Label(image=test)
    label1.image = test
    label1.place(x=50,y=5)
    #lab=Label(a,text="Mobiles",font=("Arial",15,"bold"),fg="white",bg="blue").place(x=70,y=365)
    btn=Button(b,text="Buy now",bd=5,bg="yellow",font=("Arial",12,"bold"),command=buy_now).place(x=100,y=612)
    btn=Button(b,text="Details",bd=5,bg="yellow",font=("Arial",12,"bold"),command=details).place(x=300,y=612)
    b.mainloop()
oppo_8()
