from tkinter import *
def oukitel():
    import tkinter
    from PIL import ImageTk, Image
    #import QR_Code 
    b=Tk()
    b.title("OUKITEL C20")
    b.minsize(520,655)
    b.maxsize(520,655)
    def qr():
        b.minsize(500,600)
        b.maxsize(500,600)
        image1 = Image.open('qrcode.jpg')
        test = ImageTk.PhotoImage(image1)
        label1 = tkinter.Label(image=test)
        label1.image = test
        label1.pack()
        b.mainloop()
    def details():
        print("==========================================================================")
        print("\nOUKITEL C21 Unlocked Cellphones 64GB+4GB 6.4”FHD+ Smartphones Unlock Helio P60 20MP Front Camera 4")
        print("Rear Cameras 4000mAh Battery Mobile Phone 4G Dual SIM Face ID&Fingerprint Blue\n")
        print("Price : $159.99")
        print("\nModel Name : C20")
        print("Wireless Carrier : Unlocked for All Carriers")
        print("Brand : OUKITEL")
        print("Form Factor : Smartphone")
        print("Memory Storage Capacity : 64 GB")
        print("Cellular Technology : 4G")
        print("Operating System : 10.0")
        print("Color : Blue")
        print("SIM card slot count : Dual SIM")
        print("Display Size  : 6.4 inches")
        print("\nAbout this item\n")
        print("1.) {C21 equipped with powerful CPU Helio P60 processor} MediaTek Helio P60 octa-core processor with 12nm chip technology and")
        print("4GB RAM+64GB ROM will effectively reduce power consumption and provide a wonderful user experience. C21 can easily run")
        print("multiple heavy applications and games. The 64GB ROM can store a large number of photos, videos, music, games, etc., and can run large-capacity games comfortably")
        print("2.) {6.4-inch 2310x1080 FHD+ screen display} OUKITEL C21 has a 6.4-inch 2310x1080 FHD+ display. The large ultra-high-definition")
        print("screen will take your viewing experience to a new level. You can play games, watch videos and surf the Internet comfortably")
        print("3.) {Front 20MP AI camera + rear 4 cameras, shoot high-quality photos} C21 has a rear 4 camera 16MP main camera + 2MP macro")
        print("camera + 2MP depth camera + 2MP auxiliary camera, 4 cameras can work together at the same time, shooting more Clear and")
        print("perfect photos. The front 20MP camera uses a precise algorithm to shoot people specifically, so you can capture your highlights at any time")
        print("4.) [Latest Android 10.0 system] OUKITEL C21 is equipped with the latest Android 10.0 (Android Q) system, which is more")
        print("comfortable and smoother than Android 9.0. Improve your eye health and further enhance privacy protection by adding night mode and privacy protection function")
        print("5.) [Face recognition&fingerprint unlocking and 4000mAh battery]. The dual SIM dual standby mobile phone C21 supports face")
        print("recognition and fingerprint unlocking. You can unlock it within 0.1 seconds. Protect your personal data more securely. With a")
        print("4000mAh battery, it can last all day, so you don’t have to worry about the power shortage.")
    def buy_now():
            qr()
    image1 = Image.open('out.jpg').resize((400,600))
    test = ImageTk.PhotoImage(image1)
    label1 = tkinter.Label(image=test)
    label1.image = test
    label1.place(x=50,y=5)
    #lab=Label(a,text="Mobiles",font=("Arial",15,"bold"),fg="white",bg="blue").place(x=70,y=365)
    btn=Button(b,text="Buy now",bd=5,bg="yellow",font=("Arial",12,"bold"),command=buy_now).place(x=100,y=612)
    btn=Button(b,text="Details",bd=5,bg="yellow",font=("Arial",12,"bold"),command=details).place(x=300,y=612)
    b.mainloop()
oukitel()
