from tkinter import *
def tcl():
    import tkinter
    from PIL import ImageTk, Image
    #import QR_Code 
    b=Tk()
    b.title("TCL 20 pro")
    b.minsize(570,655)
    b.maxsize(570,655)
    def qr():
        b.minsize(500,600)
        b.maxsize(500,600)
        image1 = Image.open('qrcode.jpg')
        test = ImageTk.PhotoImage(image1)
        label1 = tkinter.Label(image=test)
        label1.image = test
        label1.pack()
        b.mainloop()
    def details():
        print("==========================================================================")
        print("\nTCL 20 Pro 5G Unlocked Android Smartphone with 6.67” AMOLED FHD+ Display, 48MP OIS Quad Rear")
        print("Camera System, 6GB+256GB, 4500mAh Battery with Wireless Charging, US 5G Version Cellphone, Marine Blue")
        print("Price : $499.99")
        print("\nModel Name : TCL 20 Pro 5G")
        print("Wireless Carrier : Unlocked for All Carriers")
        print("Brand : TCL")
        print("Form Factor : Smartphone")
        print("Memory Storage Capacity : 256 GB")
        print("Operating System : Android 10.0")
        print("Color : Marine Blue")
        print("SIM card slot count : Single SIM")
        print("Display Size  : 6.2 inches AMOLED")
        print("Manufacturer : TCL\n")
        print("\nAbout this item\n")
        print("1.) Unlocked For All Carriers: The smartphone compatible with T-Mobile, Verizon 5G & LTE")
        print("networks and AT&T LTE network (without AT&T 5G support). If your device is not")
        print("receiving messages or experiences an error when making phone calls on Verizon, your")
        print("account may need to be provisioned to support “CDMA-less” devices. To do this, please")
        print("contact Verizon’s technical support team or your account’s business representative for")
        print("assistance. This device is not compatible with CDMA networks.\n")
        print("2.) The Power of 5G: Experience revolutionary speeds, faster streaming, quicker downloads,")
        print("as well as enhanced AI features and hyper-accurate GPS with the Qualcomm")
        print("Snapdragon 750G 5G Mobile processor. And 6GB of RAM provide effortlessly smooth")
        print("performance. More sharing, more gaming, more experiences, never miss a beat.\n")
        print("3.) NXTVISION 2.0 Intelligent Display: Discover seamless visuals that go beyond the edge")
        print("with the TCL 20 Pro 5G smartphone's 6.67-inch FHD+ NXTVISION AMOLED Dotch")
        print("Display. Immerse yourself in a vivid, true-to-life visual world. The phone's AI visual")
        print("enhancement intelligently detects your environment's lighting and automatically")
        print("enhances brightness, color, clarity, and contrast for the best visuals.\n")
        print("4.) 48MP OIS Quad Camera: Capture sharp photos and videos with the 48MP Optical Image")
        print("Stabilization (OIS) main camera. The 16MP ultra wide-angle, 5MP macro, and 2MP depth")
        print("camera allow you to capture and explore more of the world around you. The 32MP front")
        print("camera with dedicated RGB sensor accurately captures skin tone and natural lighting for")
        print("stunning selfies\n")
        print("5.) Keep More: 256GB ROM storage gives you enough space to keep all your apps, picture,")
        print("videos, music and files without feeling the pinch. You can also expand up to 1TB with a")
        print("microSD card (sold separately). the in-display fingerprint sensor and face unlock provide")
        print("for fast and secure access.\n")
    def buy_now():
            qr()
    image1 = Image.open('tcl_20.jpg').resize((500,600))
    test = ImageTk.PhotoImage(image1)
    label1 = tkinter.Label(image=test)
    label1.image = test
    label1.place(x=50,y=5)
    #lab=Label(a,text="Mobiles",font=("Arial",15,"bold"),fg="white",bg="blue").place(x=70,y=365)
    btn=Button(b,text="Buy now",bd=5,bg="yellow",font=("Arial",12,"bold"),command=buy_now).place(x=110,y=612)
    btn=Button(b,text="Details",bd=5,bg="yellow",font=("Arial",12,"bold"),command=details).place(x=400,y=612)
    b.mainloop()
tcl()
